name: "hamesh"
description: "homeassistant Bluetoth mesh"
version: "0.1"
slug: "hamesh"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  app:
    build: .
    volumes:
      - ../config/hamesh/:/var/lib/bluetooth/mesh
    restart: "always"
    network_mode: "host"
    privileged: true
    tty: true
