version: "3.9"
services:
  app:
    build: .
    volumes:
      - /usr/share/hassio/homeassistant/hamesh/:/var/lib/bluetooth/mesh
      - /run/dbus:/run/dbus:ro
    restart: "always"
    network_mode: "host"
    privileged: true
    tty: true
