version: "3.9"
services:
  app:
    build: .
    volumes:
    - /mnt/data/supervisor/homeassistant/:/var/lib/bluetooth/mesh
    restart: "always"
    network_mode: "host"
    privileged: true
    tty: true
